In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Loading the dataset
df=pd.read_csv('mushrooms.csv')

In [4]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [6]:
df.shape

(8124, 23)

In [8]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [10]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

### Preprocessing

In [11]:
#checking the null values
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

There is no null values in this dataset.

In [14]:
#Encoding
from sklearn.preprocessing import LabelEncoder
mappings = list()
encoder = LabelEncoder()
for column in range(len(df.columns)):
    df[df.columns[column]] = encoder.fit_transform(df[df.columns[column]])
    mappings_dict = {index: label for index, label in enumerate(encoder.classes_)}
    mappings.append(mappings_dict)

In [15]:
mappings

[{0: 'e', 1: 'p'},
 {0: 'b', 1: 'c', 2: 'f', 3: 'k', 4: 's', 5: 'x'},
 {0: 'f', 1: 'g', 2: 's', 3: 'y'},
 {0: 'b',
  1: 'c',
  2: 'e',
  3: 'g',
  4: 'n',
  5: 'p',
  6: 'r',
  7: 'u',
  8: 'w',
  9: 'y'},
 {0: 'f', 1: 't'},
 {0: 'a', 1: 'c', 2: 'f', 3: 'l', 4: 'm', 5: 'n', 6: 'p', 7: 's', 8: 'y'},
 {0: 'a', 1: 'f'},
 {0: 'c', 1: 'w'},
 {0: 'b', 1: 'n'},
 {0: 'b',
  1: 'e',
  2: 'g',
  3: 'h',
  4: 'k',
  5: 'n',
  6: 'o',
  7: 'p',
  8: 'r',
  9: 'u',
  10: 'w',
  11: 'y'},
 {0: 'e', 1: 't'},
 {0: '?', 1: 'b', 2: 'c', 3: 'e', 4: 'r'},
 {0: 'f', 1: 'k', 2: 's', 3: 'y'},
 {0: 'f', 1: 'k', 2: 's', 3: 'y'},
 {0: 'b', 1: 'c', 2: 'e', 3: 'g', 4: 'n', 5: 'o', 6: 'p', 7: 'w', 8: 'y'},
 {0: 'b', 1: 'c', 2: 'e', 3: 'g', 4: 'n', 5: 'o', 6: 'p', 7: 'w', 8: 'y'},
 {0: 'p'},
 {0: 'n', 1: 'o', 2: 'w', 3: 'y'},
 {0: 'n', 1: 'o', 2: 't'},
 {0: 'e', 1: 'f', 2: 'l', 3: 'n', 4: 'p'},
 {0: 'b', 1: 'h', 2: 'k', 3: 'n', 4: 'o', 5: 'r', 6: 'u', 7: 'w', 8: 'y'},
 {0: 'a', 1: 'c', 2: 'n', 3: 's', 4: 'v', 5: 'y

In [17]:
y = df['class']
X = df.drop('class', axis=1)

In [18]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [21]:
X

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
0      1.029712     0.140128  -0.198250  1.185917  0.881938         0.162896   
1      1.029712     0.140128   1.765874  1.185917 -1.970316         0.162896   
2     -2.087047     0.140128   1.373049  1.185917 -0.544189         0.162896   
3      1.029712     0.953270   1.373049  1.185917  0.881938         0.162896   
4      1.029712     0.140128  -0.591075 -0.843230  0.406562         0.162896   
...         ...          ...        ...       ...       ...              ...   
8119  -0.216992     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8120   1.029712     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8121  -0.840343     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8122  -0.216992     0.953270  -0.198250 -0.843230  1.832689         0.162896   
8123   1.029712     0.140128  -0.198250 -0.843230  0.406562        -6.138869   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0        -0.438864   1.494683   -0.228998    -1.144806  ...   
1        -0.438864  -0.669038   -0.228998    -1.144806  ...   
2        -0.438864  -0.669038    0.053477    -1.144806  ...   
3        -0.438864   1.494683    0.053477    -1.144806  ...   
4         2.278612  -0.669038   -0.228998     0.873511  ...   
...            ...        ...         ...          ...  ...   
8119     -0.438864  -0.669038    1.748325    -1.144806  ...   
8120     -0.438864  -0.669038    1.748325    -1.144806  ...   
8121     -0.438864  -0.669038    0.053477    -1.144806  ...   
8122     -0.438864   1.494683   -1.358896     0.873511  ...   
8123     -0.438864  -0.669038    1.748325    -1.144806  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                     0.586385                0.622441   
1                     0.586385                0.622441   
2                     0.586385                0.622441   
3                     0.586385                0.622441   
4                     0.586385                0.622441   
...                        ...                     ...   
8119                  0.586385               -0.429288   
8120                  0.586385               -0.429288   
8121                  0.586385               -0.429288   
8122                 -0.893053                0.622441   
8123                  0.586385               -0.429288   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                   0.631991        0.0    0.142037    -0.256132   0.948081   
1                   0.631991        0.0    0.142037    -0.256132   0.948081   
2                   0.631991        0.0    0.142037    -0.256132   0.948081   
3                   0.631991        0.0    0.142037    -0.256132   0.948081   
4                   0.631991        0.0    0.142037    -0.256132  -1.272216   
...                      ...        ...         ...          ...        ...   
8119               -0.416681        0.0   -3.979055    -0.256132   0.948081   
8120               -0.416681        0.0   -8.100146    -0.256132   0.948081   
8121               -0.416681        0.0   -3.979055    -0.256132   0.948081   
8122                0.631991        0.0    0.142037    -0.256132  -1.272216   
8123               -0.416681        0.0   -3.979055    -0.256132   0.948081   

      spore-print-color  population   habitat  
0             -0.670195   -0.514389  2.030028  
1             -0.250471   -1.313108 -0.295730  
2             -0.250471   -1.313108  0.867149  
3             -0.670195   -0.514389  2.030028  
4             -0.250471   -2.910546 -0.295730  
...                 ...         ...       ...  
8119          -1.509643   -2.111827  0.285710  
8120          -1.509643    0.284330  0.285710  
8121          -1.509643   -2.111827  0.285710  
8122           1.428426    0.284330  0.285710  
8123           0.169254   -2.111827  0.285710  

[8124 rows x 22 columns]

### Model Selection

In [24]:
#Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

### Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression()

In [26]:
pred = logmodel.predict(X_test)

In [27]:
pred

array([0, 1, 1, ..., 1, 0, 0])

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [30]:
accuracy=accuracy_score(y_test,pred)*100
accuracy

95.15996718621821

In [31]:
confusion_matrix(y_test,pred)

array([[1197,   60],
       [  58, 1123]], dtype=int64)

### Decision Tree Classifier

In [32]:
from sklearn.tree import DecisionTreeClassifier
dec= DecisionTreeClassifier()
dec.fit(X_train,y_train)
y_pred_decc = dec.predict(X_test)

In [33]:
f1_dt=f1_score(y_test, y_pred_decc)*100
f1_dt

100.0

In [34]:
acc_dt= accuracy_score(y_test, y_pred_decc)*100
acc_dt

100.0

### Gaussian Naive Bayes

In [35]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

In [36]:
ypred = clf.predict(X_test)
confusion_matrix(ypred, y_test), f1_score(ypred, y_test)

(array([[1172,   87],
        [  85, 1094]], dtype=int64),
 0.9271186440677965)

In [37]:
ypred

array([0, 1, 1, ..., 1, 0, 0])

In [38]:
accuracy_gnb= accuracy_score(y_test,ypred)*100
accuracy_gnb

92.9450369155045